use_frameworks!

platform :ios, '8.0'

target 'ComponentModuleCCategory_Example' do
  pod 'ComponentModuleCCategory', :path => '../'

  target 'ComponentModuleCCategory_Tests' do
    inherit! :search_paths

    
  end
end
